### ISSUE TITLE
let's organize ourselves!

### ISSUE THREAD

**Issue by laurentperrinet** [SpikeAI/2022-11_brainhack_DetecSpikMotifs#1]
One first objective is to learn how we may use GitHub issues to organize our project! 

Please answer to this issue to see if that works...

**Comment by AuroreSB** [comment]
Bonjour

**Comment by laurentperrinet** [comment]
Bonjour @AuroreSB !

Le 28 nov. 2022 à 14:06, AuroreSB ***@***.***> a écrit :



Bonjour
